site_name: Autovermietung
nav:
  - Autovermietung: index.md
  - Startseite: start.md
  - Fahrzeugverwaltung: car-management.md
  - Kundenverwaltung: customer-management.md
  - Buchungsverwaltung: booking-management.md
  - Einstellungen: settings.md
theme: readthedocs
